### PR TITLE
app-emulation/wine-staging: Pass CFLAGS to mingw

### PR DESCRIPTION
**Pull request by FireBurn**
This requires setting CROSSCFLAGS

Also filter problematic ldflags

-Wl,--hash-style*
-Wl,--as-needed

Signed-off-by: Mike Lothian <mike@fireburn.co.uk>

### CODE REVIEW

**Comment by Chiitoo** [comment]
Per a comment in bug 736657 [1], I'm not sure the stripping is still required?

1. https://bugs.gentoo.org/736657#c7

**Comment by FireBurn** [comment]
Is that better?

**Comment by Chiitoo** [comment]
Seems to work for me.

@sarnex?

Thanks!

**Comment by sarnex** [comment]
Change looks good. Should we do this for wine-vanilla too?

**Comment by FireBurn** [comment]
I've not tested wine vanilla, might be worth checking it doesn't have those flag issues

**Comment by sarnex** [comment]
I wouldn't expect it to be any different. Can you please make the same change for wine-vanilla in this PR? Thanks

**Comment by FireBurn** [comment]
Added vanilla too

Should the tc-export's be sync'd? If you let me know if AR & RANLIB are needed I'll get them added to the -r2's and 9999s where they're missing

**Comment by sarnex** [comment]
Thanks, I think we're good for now. Chiitoo tested it so I'll just pull. Thanks for the contribution

**Pull request closed without merging**
