### PR TITLE
app-emulation/wine-mono: add shared support

### PR DESCRIPTION
**Pull request by Hello71**
Signed-off-by: Alex Xu (Hello71) <alex_y_xu@yahoo.ca>

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
Do you need me to push this?

**Comment by Hello71** [comment]
what do you mean?

**Comment by sarnex** [comment]
Like commit this code

**Comment by Hello71** [comment]
i don't understand what you mean by "need". i have been testing this change for some months in my overlay. i would like to contribute it for other users to use. since i am not allowed to push to gentoo or wine repositories, i have opened PRs for review and merging. if you want to accept it, i would appreciate it. if you do not, i will continue to maintain it myself.

**Comment by thesamesam** [comment]
@Hello71 He was just asking if you had privileges to commit/push it to the repository yourself.

**Comment by sarnex** [comment]
Yeah sorry I wasn't sure if you had push permission. I'll push it now. Thanks for your contribution.

**Pull request closed without merging**
