### PR TITLE
app-emulation/wine: Update pkg_pretend to allow bin installs

### PR DESCRIPTION
**Pull request by FireBurn**
These are building from source checks and aren't neccessary when
installing from a bin package

Signed-off-by: Mike Lothian <mike@fireburn.co.uk>

### CODE REVIEW

**Comment by sarnex** [comment]
The src_pretend phase doesn't exist. I confirmed this by adding a universal "die" call to pkg_pretend, verifying it gets hit, renaming it to src_pretend, and verifying it doesn't

**Comment by FireBurn** [comment]
Crap, sorry

[00:57] <ionen> FireBurn: ah, not just that, look at firefox's pkg_setup, there's a check for MERGE_TYPE
[00:57] <grknight> FireBurn: fwiw, binpkgs all run pkg_* phases and skip the src_* ones

I'll do some more digging and find a better solution

**Comment by FireBurn** [comment]
This allows me to install bin packages, incorporates the changes I made to allow release candidate ebuilds and resyncs the live and the non-live ebuilds

**Comment by sarnex** [comment]
No plans for this one at the moment

**Pull request closed without merging**
